name = "My Modpack"
author = "HxiaoH"
version = "26.9.14.11.34"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d76252f1a9a4f4b0e01ad54e562d79f521f2793a838928cfaef89bfddee4ade"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"

[options]
datapack-folder = "datapacks"
