name = "HxiaoH's NeoForge Server"
author = "HxiaoH"
version = "26.10.6.11.40"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d0ed09d0476b02a5abb23d6c41ee085e8ae864a12823aec795bb9aeca90462c1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"

[options]
datapack-folder = "datapacks"
