name = "My Modpack"
author = "HxiaoH"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d06c9d81b8ef18233e0473b4b8a95f397430a857264052408917100bdd249ecc"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.247"

[options]
datapack-folder = "datapacks"
